// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdv9Hm7e9uHNNcZqZ30WihyAZ61EsYrus',
    appId: '1:132180033855:web:3fcf05d612ee92b307538a',
    messagingSenderId: '132180033855',
    projectId: 'whatsapp-backend-faf66',
    authDomain: 'whatsapp-backend-faf66.firebaseapp.com',
    storageBucket: 'whatsapp-backend-faf66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNzqAIu6WKoNUJr4gRwDqjl2sdGFIikpY',
    appId: '1:132180033855:android:84e3cb1b64f7218f07538a',
    messagingSenderId: '132180033855',
    projectId: 'whatsapp-backend-faf66',
    storageBucket: 'whatsapp-backend-faf66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV3kUqkHCO4M6xgS4OQOEaZKMmLA0HLZM',
    appId: '1:132180033855:ios:5be6d4ee833a204507538a',
    messagingSenderId: '132180033855',
    projectId: 'whatsapp-backend-faf66',
    storageBucket: 'whatsapp-backend-faf66.appspot.com',
    iosBundleId: 'com.example.mike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV3kUqkHCO4M6xgS4OQOEaZKMmLA0HLZM',
    appId: '1:132180033855:ios:5f44cccbe3daeae007538a',
    messagingSenderId: '132180033855',
    projectId: 'whatsapp-backend-faf66',
    storageBucket: 'whatsapp-backend-faf66.appspot.com',
    iosBundleId: 'com.example.mike.RunnerTests',
  );
}
